apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
      - image: sjc.vultrcr.com/workshopton/backend-mock:latest
        name: backend-mock
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    app: my-deployment
  type: ClusterIP

---
 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-deployment
spec:
  rules:
  - host: sanches.diadecloud.com
    http:
      paths:
      - backend:
          service:
            name: my-deployment
            port:
              name: http
        path: /
        pathType: Prefix




